Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2019-12, with the labels that each got.

#625 playfair cipher encryption
  Others/PlayfairCipher.cpp
Labels: on hold

#677 GitHub Action: Compile modified files with g++
  .github/workflows/cpplint_modified_files.yml
Labels: on hold

#589 Matrix Exponentiation
  .DS_Store
  Others/.DS_Store
  Others/a.out
  others/matrix_exponentiation.cpp
Labels: automated tests are failing

#688 WIP: Create build_directory_md_new.yml
  .github/scripts/build_directory_md.py
  .github/workflows/build_directory_md.yml
  .github/workflows/update_directory_md.yml
  DIRECTORY.md
Labels: awaiting modification, on hold
