Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2019-11, with the labels that each got.

#137 Program for Huffman Coding in C++
  Greedy Algorithms/huffman.cpp
Labels: on hold

#629 Add template for bug and feature as issue
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, ready for review

#631 Feat: Add/Format Readme.md Contribution.md and pull-request-template.md
  .github/pull_request_template.md
  CONTRIBUTION.md
  README.md
Labels: enhancement, ready for review

#630 Add Pascal's Triangle Algorithm
  Others/pascal_triangle.cpp
Labels: on hold

#639 GitHub Action to run cpplint on all pull requests
  .github/workflows/ccpp.yml
Labels: ready for review, testing
