Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2020-10, with the labels that each got.

#1068 Created jumpgame.cpp
  greedy_algorithms/jumpgame.cpp
Labels: approved, enhancement

#1273 docs: Update comments to English in sudoku_solve.cpp
  backtracking/sudoku_solve.cpp
Labels: Improvement, approved

#1135 [fix/feat]: Added Code of Conduct
  CODE_OF_CONDUCT.md
Labels: approved, enhancement

#1087 Hopcroft–Karp algorithm implementation
  DIRECTORY.md
  graph/hopcroft_karp.cpp
Labels: approved, enhancement

#1084 [fix/docs]: Improve backtracking/rat_maze.cpp
  backtracking/rat_maze.cpp
Labels: Improvement, approved

#996 Added Sparse Table for range query
  DIRECTORY.md
  range_queries/sparse_table.cpp
Labels: abandoned, approved, enhancement

#1278 adding word break DP approach
  DIRECTORY.md
  dynamic_programming/word_break.cpp
Labels: approved, enhancement

#1189 feat: Add Pancake Sort algorithm
  DIRECTORY.md
  sorting/pancake_sort.cpp
Labels: approved, enhancement

#1302 feat: guidelines for reviewers
  REVIEWER_CODE.md
Labels: approved, enhancement

#1207 added documentation in `dynamic_programming/0_1_knapsack.cpp`
  dynamic_programming/0_1_knapsack.cpp
Labels: Improvement, approved

#1331 docs: Imporoved Documentation in neural_network.cpp
  machine_learning/neural_network.cpp
Labels: Improvement, approved

#1300 [fix/docs]: Improve CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, enhancement

#1041 [fix/docs]: Improve backtracking/n_queens_all_solution_optimised.cpp
  backtracking/n_queens_all_solution_optimised.cpp
  sorting/pancake_sort.cpp
Labels: Improvement, ready for review

#1322 feat: Added Morse Code
  DIRECTORY.md
  ciphers/morse_code.cpp
Labels: approved, enhancement

#1264 fix: remove `using namespace std` in greedy_algorithms/kruskals_minimum_spanning_tree.cpp
  greedy_algorithms/kruskals_minimum_spanning_tree.cpp
Labels: Improvement, approved

#1252 feat: add cycle sort algorithm
  DIRECTORY.md
  sorting/cycle_sort.cpp
Labels: approved, enhancement

#1342 fix: Issue in list_array.cpp resolved
  data_structures/list_array.cpp
Labels: Improvement, approved

#1359 Modified the source for wider range of inputs
  graph/breadth_first_search.cpp
Labels: Improvement

#1319 feat: add palindrome partitioning algorithm
  DIRECTORY.md
  dynamic_programming/palindrome_partitioning.cpp
Labels: approved, enhancement

#1344 feat: add lcm_sum.cpp
  DIRECTORY.md
  math/lcm_sum.cpp
Labels: approved, enhancement

#1363 feat: add sum_of_binomial_coefficients
  DIRECTORY.md
  math/sum_of_binomial_coefficient.cpp
Labels: approved, enhancement

#1265 feat: add wiggle sort algorithm
  DIRECTORY.md
  sorting/wiggle_sort.cpp
Labels: approved, enhancement

#1276 feat: Add modular_exponentiation.cpp
  DIRECTORY.md
  math/modular_exponentiation.cpp
Labels: approved, enhancement

#1321 feat/fix: Improve numerical_methods/false_position.cpp
  numerical_methods/false_position.cpp
Labels: Improvement, approved

#1286 feat: Add Runge Kutta Method
  DIRECTORY.md
  numerical_methods/rungekutta.cpp
Labels: approved, enhancement

#1378 feat: Coin Change Problem
  DIRECTORY.md
  dynamic_programming/coin_change_topdown.cpp
Labels: approved, enhancement

#1339 feat: Add Gram Schmidt Orthogonalisation
  DIRECTORY.md
  linear_algebra/gram_schmidt.cpp
Labels: approved, enhancement
