Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2020-08, with the labels that each got.

#991 fix: linter warnings for bridge finding algorithm.
  graph/bridge_finding_with_tarjan_algorithm.cpp
Labels: Improvement, approved

#993 fix: linter warnings for topological_sort_by_kahns_algo
  graph/topological_sort_by_kahns_algo.cpp
Labels: Improvement, approved

#992 fix: linter warnings for connected_components_with_dsu.
  graph/connected_components_with_dsu.cpp
Labels: Improvement, requested changes

#994 fix: linter warnings for topological_sort.
  graph/topological_sort.cpp
Labels: Improvement, requested changes

#916 [fix/docs]: Update backtracking folder
  CMakeLists.txt
  backtracking/CMakeLists.txt
  backtracking/graph_coloring.cpp
  backtracking/knight_tour.cpp
  backtracking/minimax.cpp
  backtracking/sudoku_solve.cpp
Labels: Improvement

#990 fix: refactor BFS algorithm.
  graph/bfs.cpp
  graph/breadth_first_search.cpp
Labels: Improvement, approved

#998 fix: linter for prim.
  graph/prim.cpp
Labels: Improvement, approved

#1021 [enhancement] update openmp version & doxygen path fix
  CMakeLists.txt
Labels: approved, enhancement

#1000 [fix/docs]: Improve backtracking/n_queens.cpp
  backtracking/n_queens.cpp
Labels: Improvement, approved

#980 Refactor lowest comomon ancestor.
  DIRECTORY.md
  graph/lca.cpp
  graph/lowest_common_ancestor.cpp
Labels: Improvement, approved

#1024 fix: spelling typo
  graph/lowest_common_ancestor.cpp
Labels: bugfix, ready for review

#1018 Added is_graph_bipartite.cpp
  graph/is_graph_bipartite.cpp
Labels: approved, enhancement

#1023 test: add test for fibonacci() function
  math/fibonacci.cpp
Labels: Improvement, approved

#1033 fix: linter for dijkstra
  graph/dijkstra.cpp
Labels: Improvement, approved

#1034 fix: linter for connected_components.
  graph/connected_components.cpp
Labels: Improvement, approved

#1027 Added Jarvis Algorithm to compute convex hull
  geometry/jarvis_algorithm.cpp
Labels: approved, enhancement

#1036 fix: linter for kruskal
  graph/kruskal.cpp
Labels: Improvement, approved

#1035 fix: linter for kosaraju
  graph/kosaraju.cpp
Labels: Improvement, approved

#1030 feat: add shortest common super-sequence algorithm
  DIRECTORY.md
  dynamic_programming/shortest_common_supersequence.cpp
Labels: approved, enhancement

#986 fhlasek/fixgraph: refactor of graph/ to follow the linter style
  CMakeLists.txt
  DIRECTORY.md
  graph/CMakeLists.txt
  graph/cycle_check_directed_graph.cpp
  graph/depth_first_search.cpp
  graph/depth_first_search_with_stack.cpp
  graph/dfs.cpp
  graph/dfs_with_stack.cpp
Labels: Improvement, approved

#1025 feat: Add Neural Network (Multilayer Perceptron)
  machine_learning/iris.csv
  machine_learning/neural_network.cpp
  machine_learning/vector_ops.hpp
Labels: enhancement, requested changes

#1016 Added heavy_light_decomposition.cpp
  DIRECTORY.md
  range_queries/heavy_light_decomposition.cpp
Labels: approved, enhancement

#1050 fix typo: (rename file) fast_interger_input -> fast_integer_input
  others/fast_integer_input.cpp
Labels: approved, bugfix

#1028 feat: add Pigeonhole algorithm
  sorting/pigeonhole_sort.cpp
Labels: approved, enhancement

#1044 fix: error handling in opening of external files (neural_network.cpp).
  machine_learning/neural_network.cpp
  machine_learning/vector_ops.hpp
Labels: Improvement, approved

#1037 fix: linter and spacing for is_graph_bipartite.
  graph/is_graph_bipartite.cpp
Labels: Improvement, approved

#1056 fix: clang-format for graph/
  graph/CMakeLists.txt
  graph/breadth_first_search.cpp
  graph/bridge_finding_with_tarjan_algorithm.cpp
  graph/depth_first_search_with_stack.cpp
  graph/kosaraju.cpp
  graph/kruskal.cpp
  graph/lowest_common_ancestor.cpp
  graph/max_flow_with_ford_fulkerson_and_edmond_karp_algo.cpp
  graph/prim.cpp
  graph/topological_sort.cpp
  graph/topological_sort_by_kahns_algo.cpp
Labels: Improvement, approved

#1055 fix: clang-format for dijkstra
  graph/dijkstra.cpp
Labels: Improvement, approved

#1054 fix: clang-format for hamiltons_cycle.
  graph/hamiltons_cycle.cpp
Labels: Improvement, approved

#1058 docs: Corrected the typo in the file
  strings/knuth_morris_pratt.cpp
Labels: Improvement, approved

#1059 [code fix] Fixed trie_tree for code quality and docs & clang-tidy error check
  .clang-tidy
  data_structures/trie_tree.cpp
Labels: Improvement, bugfix

#1053 docs: Update clang-format instructions in CONTRIBUTING.
  CONTRIBUTING.md
Labels: Improvement

#1067 [fix/docs]: Code improvements in Fibbonacci algorithm. Code is documented.
  dynamic_programming/fibonacci_top_down.cpp
Labels: Improvement, approved
