Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2020-05, with the labels that each got.

#759 Create extended_euclid_algorithm.cpp
  DIRECTORY.md
  math/extended_euclid_algorithm.cpp
Labels: awaiting modification

#754 SwapSort.cpp
  sorting/swap_sort.cpp
Labels: automated tests are failing

#772 fix #765: Doubly Linked List algorithm bug
  data_structure/Doubly Linked List.cpp
  data_structure/doubly_linked_list.cpp
Labels: awaiting modification

#788 CONTRIBUTING.md: Don’t open issues asking to be assigned
  CONTRIBUTION.md
Labels: ready for review
