Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2020-09, with the labels that each got.

#1062 feat: Added merge-insertion sort from #246
  DIRECTORY.md
  data_structures/skip_list.cpp
  sorting/merge_insertion_sort.cpp
Labels: Improvement, approved, enhancement

#999 Revised Linked List
  data_structures/linked_list.cpp
Labels: Improvement, approved

#1071 Added Horspool algorithm
  strings/horspool.cpp
Labels: approved, enhancement

#1077 Update merge_sort.cpp
  sorting/merge_sort.cpp
Labels: Improvement, approved

#1076 feat: Define graph structure in breadth_first_search
  graph/breadth_first_search.cpp
Labels: Improvement, approved

#1079 added kadane algorithm function
  dynamic_programming/kadane2.cpp
Labels: approved, enhancement

#1066 Merge sort
  sorting/merge_sort.cpp
Labels: Improvement, approved

#1081 Added strand sort algorithm
  DIRECTORY.md
  sorting/strand_sort.cpp
Labels: approved, enhancement

#1085 [fix]: `dynamic_programming/cut_rod.cpp` does not compile
  dynamic_programming/cut_rod.cpp
  dynamic_programming/kadane2.cpp
Labels: Improvement, approved

#1083 feat: Added Postfix Evaluation
  DIRECTORY.md
  others/postfix_evaluation.cpp
Labels: approved, enhancement
