Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2021-09, with the labels that each got.

#1570 feat: Add inverse inverse root functions
  DIRECTORY.md
  math/inv_sqrt.cpp
Labels: enhancement, approved

#1582 fix: Fixed typo in README.md
  README.md
Labels: good first issue, bugfix, approved

#1497 feat: Finding no. of digits in a Number
  DIRECTORY.md
  math/finding_number_of_digits_in_a_number.cpp
  search/floyd_cycle_detection_algo.cpp
  sorting/dnf_sort.cpp
Labels: enhancement, approved

#1581 feat: added z_algorithm in strings
  DIRECTORY.md
  strings/z_function.cpp
Labels: enhancement, approved

#1589 fix: Add `return 0` in `bactracking/magic_sequence.cpp`
  backtracking/magic_sequence.cpp
Labels: good first issue, Improvement, approved

#1578 feat: Add the Selection Sort Recursive algorithm
  DIRECTORY.md
  sorting/selection_sort_recursive.cpp
Labels: enhancement, approved

#1590 feat: Add Travelling Salesman Problem(Naive Approach)
  DIRECTORY.md
  graph/travelling_salesman_problem.cpp
Labels: enhancement, approved

#1605 Add working workflow for stale items
  .github/stale.yml
  .github/workflows/stale.yml
Labels: enhancement

#1607 feat: Unleash full power of the stale workflow
  .github/workflows/stale.yml
Labels: enhancement

#1595 feat: Add MD5 Hashing Algorithm
  DIRECTORY.md
  hashing/md5.cpp
  sorting/selection_sort_recursive.cpp
Labels: enhancement, approved

#1609 feat. Add SHA-1 hashing algorithm
  DIRECTORY.md
  hashing/sha1.cpp
Labels: enhancement, approved

#1596 feat: Add reverse linked list algorithim
  DIRECTORY.md
  data_structures/reverse_a_linked_list.cpp
Labels: enhancement, approved
