Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2021-06, with the labels that each got.

#1502 feat: add spare table data structure
  DIRECTORY.md
  data_structures/sparse_table.cpp
Labels: approved, enhancement

#1504 [feat/fix/docs]: Improve the `dynamic_programming/longest_increasing_subsequence.cpp` file
  dynamic_programming/longest_increasing_subsequence.cpp
Labels: Improvement, approved, ready for review

#1503 [feat/fix]: Improve the contributing guidelines
  CONTRIBUTING.md
Labels: approved, enhancement, ready for review
