Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2021-02, with the labels that each got.

#1388 fix: updated datatypes references
  dynamic_programming/cut_rod.cpp
Labels: Improvement, approved

#1215 Nth fibonacci number using matrix exponentiation
  math/fibonacci_matrix_exponentiation.cpp
Labels: awaiting modification, enhancement, good first issue, invalid

#1292 cross product of two vectors
  DIRECTORY.md
  math/vector_cross_product.cpp
Labels: approved, enhancement, hacktoberfest-accepted

#1185 feat: add longest palindromic subsequence algorithm
  dynamic_programming/longest_palindromic_subsequence.cpp
Labels: automated tests are failing, awaiting modification

#1375 [docs/test]: Documentation and test in the list_array.cpp
  data_structures/list_array.cpp
Labels: Improvement, approved

#1208 feat: add new implementation of binary search tree
  DIRECTORY.md
  data_structures/binary_search_tree2.cpp
Labels: automated tests are failing, awaiting modification, enhancement, good first issue

#1335 fix/test/docs: update variable sizes, add namespace in graph/depth_first_search_with_stack.cpp
  graph/depth_first_search_with_stack.cpp
Labels: Improvement, approved

#1445 feat: Added persistent segment tree with lazy propagation
  DIRECTORY.md
  range_queries/persistent_seg_tree_lazy_prop.cpp
Labels: approved, enhancement

#1453 feat: Setup Probot Stale app
  .github/stale.yml
Labels: approved, enhancement

#1454 fix: Updated sorting/comb_sort.cpp
  sorting/comb_sort.cpp
Labels: approved, bugfix

#1376 feat: Hamming distance algorithm.
  DIRECTORY.md
  bit_manipulation/hamming_distance.cpp
Labels: approved, enhancement

#1448 feat: add program to calculate binomial coefficients
  DIRECTORY.md
  math/binomial_calculate.cpp
Labels: approved, enhancement

#1456 feat: Multiple Variants of Search on Trie
  DIRECTORY.md
  operations_on_datastructures/trie_multiple_search.cpp
Labels: approved, enhancement
