Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2021-01, with the labels that each got.

#1438 feat: added highlighting differences in Sudoku Solver
  backtracking/sudoku_solve.cpp
Labels: Improvement, approved

#1440 fix: Update copyright notice/year to 2021
  LICENSE
Labels: enhancement

#1403 [FEATURE] Documentation improved and make some method efficient in DSU
  graph/connected_components_with_dsu.cpp
Labels: Improvement, approved

#1441 feat: added modular division algorithm
  DIRECTORY.md
  math/modular_division.cpp
Labels: approved, enhancement
