Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2021-07, with the labels that each got.

#1506 feat: Added implementation of iterative version of tree traversals.
  DIRECTORY.md
  others/iterative_tree_traversals.cpp
Labels: approved, enhancement

#1522 [feat/fix]: Guidelines improvements
  CONTRIBUTING.md
  CodingGuidelines.md
Labels: approved, enhancement

#1510 feat: add random pivot quick sort algorithm
  DIRECTORY.md
  sorting/random_pivot_quick_sort.cpp
Labels: approved, enhancement

#1513 feat: add Sublist Search Algorithm
  DIRECTORY.md
  search/sublist_search.cpp
Labels: approved, enhancement

#1515 Create count_of_set_bits.cpp
  DIRECTORY.md
  bit_manipulation/count_of_set_bits.cpp
Labels: approved, enhancement

#1530 Replace "\n" -> std::endl
  backtracking/graph_coloring.cpp
Labels: Improvement, approved

#1524 feat: Add House Robber algorithm
  DIRECTORY.md
  dynamic_programming/house_robber.cpp
Labels: approved, enhancement

#1531 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, enhancement

#1520 tests: Add test in `cycle_sort.cpp`
  sorting/cycle_sort.cpp
Labels: approved, enhancement

#1517 Create subset_sum.cpp
  DIRECTORY.md
  backtracking/subset_sum.cpp
Labels: approved, enhancement

#1525 feat: Add the Wave Sort algorithm
  DIRECTORY.md
  sorting/wave_sort.cpp
Labels: approved, enhancement

#1533 feat: solving magic sequence problem with backtracking
  DIRECTORY.md
  backtracking/magic_sequence.cpp
Labels: approved, enhancement, good first issue

#1532 feat: add inorder successor for bst in operations on ds
  DIRECTORY.md
  operations_on_datastructures/inorder_successor_of_bst.cpp
Labels: approved, enhancement

#1540 feat: Add the floyd_cycle_detection_algo.cpp file/algorithm
  search/floyd_cycle_detection_algo.cpp
Labels: enhancement

#1527 feat: Add the Subarray Sum implementation
  DIRECTORY.md
  backtracking/graph_coloring.cpp
  backtracking/subarray_sum.cpp
  others/iterative_tree_traversals.cpp
  sorting/random_pivot_quick_sort.cpp
Labels: approved, enhancement

#1545 feat: Convert all issue templates into issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  DIRECTORY.md
Labels: approved, enhancement, ready for review

#1537 Issue #1536 - [BUG] check_prime.cpp returns incorrect output for 9
  math/check_prime.cpp
Labels: bug, bugfix

#1543 feat: Add `count_of_trailing_ciphers_in_factorial_n`
  DIRECTORY.md
  bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
  math/check_prime.cpp
Labels: approved, enhancement

#1544 feat: Add `n_bonacci.cpp` in math section
  DIRECTORY.md
  math/n_bonacci.cpp
Labels: approved, enhancement, good first issue
