Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2021-10, with the labels that each got.

#1648 feat: Update stale workflow message
  .github/workflows/stale.yml
Labels: enhancement, hacktoberfest-accepted

#1553 [feat/fix/docs]: Improvements in the `backtracking` folder
  backtracking/graph_coloring.cpp
  backtracking/knight_tour.cpp
  backtracking/minimax.cpp
  backtracking/n_queens.cpp
  backtracking/n_queens_all_solution_optimised.cpp
  backtracking/nqueen_print_all_solutions.cpp
  backtracking/rat_maze.cpp
  backtracking/sudoku_solve.cpp
Labels: enhancement, approved

#1810 fix: rewrite prime numbers using linear sieve
  math/prime_numbers.cpp
Labels: Improvement, approved
