Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2021-08, with the labels that each got.

#1552 feat: Wildcard matching problem
  DIRECTORY.md
  backtracking/wildcard_matching.cpp
Labels: enhancement, approved

#1550 feat: Karatsuba algorithm
  DIRECTORY.md
  divide_and_conquer/karatsuba_algorithm_for_fast_multiplication.cpp
Labels: enhancement, approved

#1559 feat: Add endlines in `hashing/chaining.cpp`
  hashing/chaining.cpp
Labels: Improvement

#1560 fix: Minor spelling fixes in `README.md`
  README.md
Labels: enhancement, approved

#1557 feat: add lru caching algorithm
  DIRECTORY.md
  hashing/chaining.cpp
  others/lru_cache.cpp
Labels: enhancement, approved

#1558 feat: add dnf sort
  DIRECTORY.md
  sorting/dnf_sort.cpp
Labels: enhancement, requested changes

#1577 feat: add manacher's algorithm
  DIRECTORY.md
  strings/manacher_algorithm.cpp
Labels: enhancement, approved
