Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2021-11, with the labels that each got.

#1832 fix: Update the CoC to match the `.github` repository
  CODE_OF_CONDUCT.md
Labels: enhancement

#1785 feat: Created midpoint integration numerical method
  DIRECTORY.md
  graph/is_graph_bipartite2.cpp
  numerical_methods/midpoint_integral_method.cpp
Labels: enhancement, approved

#1700 feat: Implemented Fast Fourier Transform algorithm
  DIRECTORY.md
  numerical_methods/fast_fourier_transform.cpp
Labels: enhancement, approved

#1825 fix: Circular linked list
  operations_on_datastructures/circular_linked_list.cpp
Labels: Improvement, approved

#1834 feat : Implemented Inverse Fast Fourier Transform
  DIRECTORY.md
  numerical_methods/inverse_fast_fourier_transform.cpp
Labels: enhancement, approved

#1839 fix: Update Gitpod extensions
  .gitpod.yml
Labels: enhancement

#1837 feat : Implemented Babylonian Method
  DIRECTORY.md
  numerical_methods/babylonian_method.cpp
Labels: enhancement, approved

#1827 fix: CodeQL warnings
  ciphers/uint128_t.hpp
  ciphers/uint256_t.hpp
  data_structures/reverse_a_linked_list.cpp
  numerical_methods/babylonian_method.cpp
  numerical_methods/composite_simpson_rule.cpp
  numerical_methods/fast_fourier_transform.cpp
  numerical_methods/inverse_fast_fourier_transform.cpp
Labels: Improvement, approved

#1842 feat: Added Solution of Partition Problem
  DIRECTORY.md
  dynamic_programming/partition_problem.cpp
Labels: enhancement, approved

#1836 feat: Added Graham Scan Algorithm.
  DIRECTORY.md
  geometry/graham_scan_algorithm.cpp
  geometry/graham_scan_functions.hpp
  numerical_methods/inverse_fast_fourier_transform.cpp
Labels: enhancement, approved
