Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2022-11, with the labels that each got.

#2111 Backslash was not printing
  others/stairs_pattern.cpp
Labels: bugfix

#2397 fix: use FreeGlut newest GitHub link
  DIRECTORY.md
  graphics/CMakeLists.txt
Labels: bug, approved

#2399 chore(fix): `data_strcutres` -> `data_structures`
  data_structures/stack_using_queue.cpp
Labels: bugfix

#2061 add find_single_number
  bit_manipulation/find_non_repeating_number.cpp
Labels: enhancement, requested changes
