Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2022-01, with the labels that each got.

#1840 fix: CI workflow not being able to commit to the `master` branch
  .github/workflows/awesome_workflow.yml
  DIRECTORY.md
  backtracking/graph_coloringg.cpp
Labels: enhancement, approved

#1855 feat: Reworked interpolation_search.cpp
  search/interpolation_search.cpp
Labels: enhancement, approved

#1854 feat: Reworked binary_search.cpp
  search/binary_search.cpp
Labels: Improvement, approved

#1850 feat: add binary_insertion_sort
  DIRECTORY.md
  sorting/binary_insertion_sort.cpp
  strings/brute_force_string_searching.cpp
Labels: enhancement, approved

#1862 Added count_bits_flip.cpp
  DIRECTORY.md
  bit_manipulation/count_bits_flip.cpp
Labels: enhancement, approved

#1865 feat: add Recursive tree traversal techniques
  DIRECTORY.md
  others/recursive_tree_traversal.cpp
Labels: enhancement, approved

#1863 added set_kth_bit.cpp
  DIRECTORY.md
  bit_manipulation/set_kth_bit.cpp
Labels: enhancement, approved

#1860 Add approximate_pi.cpp file
  math/approximate_pi.cpp
Labels: enhancement, requested changes

#1641 docs: documentation improvements in `search/linear_search.cpp`
  search/linear_search.cpp
Labels: Improvement, approved
