Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2022-10, with the labels that each got.

#2067 fix: fixed broken link in contributing file
  CONTRIBUTING.md
Labels: bugfix

#2070 fix: `quick_sort_3.cpp` warning
  sorting/quick_sort_3.cpp
Labels: bugfix, approved

#2115 fix: karatsuba's algorithm is not compiling
  divide_and_conquer/karatsuba_algorithm_for_fast_multiplication.cpp
Labels: bugfix, approved

#2276 fix: fix markdown formatting
  dynamic_programming/kadane2.cpp
Labels: invalid, bugfix

#2201 docs: fix grammatical errors and typos
  dynamic_programming/0_1_knapsack.cpp
  dynamic_programming/armstrong_number.cpp
Labels: Improvement

#2279 feat: added physics directory and ground to ground projectile motion algorithm
  DIRECTORY.md
  physics/ground_to_ground_projectile_motion.cpp
Labels: enhancement, approved

#2329 docs: update a logically wrong doc comment
  sorting/merge_sort.cpp
Labels: bugfix

#2072 feat: add CMakeLists for the `divide_and_conquer` directory
  CMakeLists.txt
  divide_and_conquer/CMakeLists.txt
Labels: enhancement, approved
