Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2022-09, with the labels that each got.

#1983 fix(list_array): fix overflow check
  data_structures/list_array.cpp
Labels: Improvement, bugfix

#1960 Added one Useful Link
  data_structures/binary_search_tree2.cpp
Labels: Improvement, approved

#1991 feat: add the `bit_manipulation` directory to CMake
  CMakeLists.txt
  DIRECTORY.md
  bit_manipulation/CMakeLists.txt
Labels: enhancement, approved

#1953 feat: add bloom_filter to `data_structures`
  DIRECTORY.md
  data_structures/bloom_filter.cpp
Labels: enhancement

#1996 docs: improve the contributing guidelines
  CONTRIBUTING.md
Labels: Improvement, approved

#1998 Update linear_search.cpp
  search/linear_search.cpp
Labels: Improvement

#1952 fix #1951
  data_structures/reverse_a_linked_list.cpp
Labels: bugfix, dont-close
