Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2022-02, with the labels that each got.

#1897 feat: add perimeter.cpp
  DIRECTORY.md
  math/perimeter.cpp
Labels: enhancement, approved

#1931 My branch
  data_structures/linked_list.cpp
Labels: Improvement

#1640 test: Add self-test cases in the `math/power_of_two.cpp` file
  math/power_of_two.cpp
Labels: Improvement, approved
