Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2022-12, with the labels that each got.

#2396 [feat/docs]: improve the `quick_sort.cpp` algorithm
  DIRECTORY.md
  sorting/quick_sort.cpp
Labels: enhancement, approved

#2407 Discord links updated.
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/stale.yml
  CONTRIBUTING.md
  README.md
Labels: enhancement

#2408 feat: improve the Awesome Workflow
  .github/workflows/awesome_workflow.yml
  .github/workflows/codeql.yml
  .github/workflows/codeql_analysis.yml
  .github/workflows/gh-pages.yml
Labels: enhancement, bugfix, approved

#2410 docs: add guide on integrating CMake
  CONTRIBUTING.md
Labels: enhancement, approved
