Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2023-02, with the labels that each got.

#2224 feat: add power of two algorithm
  bit_manipulation/power_of_2.cpp
Labels: enhancement, stale

#2429 fix: remove memory leak in `avltree.cpp`
  DIRECTORY.md
  bit_manipulation/power_of_2.cpp
  data_structures/avltree.cpp
Labels: Improvement

#2242 feat: add maximum circular subarray sum
  DIRECTORY.md
  dynamic_programming/maximum_circular_subarray.cpp
Labels: enhancement, requested changes
