Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2023-07, with the labels that each got.

#2462 fix: cleanup `longest_common_string.cpp`
  dynamic_programming/longest_common_string.cpp
Labels: enhancement

#2500 chore: add the linter to a separate Python script
  .github/workflows/awesome_workflow.yml
  .gitignore
  scripts/file_linter.py
Labels: enhancement

#2478 feat: upgrade FreeGlut to v3.4.0
  graphics/CMakeLists.txt
Labels: enhancement, approved

#2487 docs: fit `factorial.cpp` to contribution guidelines
  math/factorial.cpp
Labels: enhancement

#2480 feat: improve the Armstrong Number algorithm
  dynamic_programming/armstrong_number.cpp
Labels: enhancement, approved

#2499 fix: fit `approximate_pi.cpp` to guidelines
  math/approximate_pi.cpp
Labels: enhancement

#2505 feat: update cmake to use a newer version
  CMakeLists.txt
Labels: enhancement

#2453 Feat: added iterativeFactorial
  math/iterative_factorial.cpp
Labels: enhancement

#2458 feat: Treap Data Structure
  data_structures/treap.cpp
Labels: enhancement

#2507 Fix wrong contributing link (#2502)
  .github/pull_request_template.md
Labels: bugfix

#2506 [feat/docs]: improve Fenwick Tree algorithm
  range_queries/fenwick_tree.cpp
Labels: Improvement, approved

#2482 docs: add documentation in `kruskals_minimum_spanning_tree.cpp`
  greedy_algorithms/kruskals_minimum_spanning_tree.cpp
Labels: Improvement, approved

#2508 [feat/docs/fix]: improve the Dijkstra algorithm
  greedy_algorithms/dijkstra.cpp
Labels: Improvement, approved
