Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2023-04, with the labels that each got.

#2234 added log code for counting digits
  math/finding_number_of_digits_in_a_number.cpp
Labels: Improvement

#2449 chore: update the CodeQL workflow
  .github/workflows/codeql.yml
Labels: enhancement, approved

#2440 feat: add Stooge sort algorithm
  sorting/stooge_sort.cpp
Labels: enhancement

#2452 docs: add self-test examples
  CONTRIBUTING.md
  DIRECTORY.md
Labels: enhancement, approved

#2444 feat: Segment Tree Data Structure
  data_structures/segment_tree.cpp
Labels: enhancement

#2451 Quadratic equations complex numbers
  math/quadratic_equations_complex_numbers.cpp
Labels: enhancement

#2447 fix: fit euler's totient to the contribution guidelines.
  math/eulers_totient_function.cpp
Labels: Improvement
