Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2023-01, with the labels that each got.

#2235 fix: remove memory leak in stack
  DIRECTORY.md
  data_structures/stack.h
  data_structures/stack.hpp
  data_structures/test_stack.cpp
  data_structures/test_stack_students.cpp
Labels: bugfix, approved

#2136 feat: Added Travelling Salesman Problem using bit-manipulation
  DIRECTORY.md
  bit_manipulation/travelling_salesman_using_bit_manipulation.cpp
Labels: enhancement

#2400 feat: Add aliquot sum of a number algorithm, class Math
  math/aliquot_sum.cpp
Labels: enhancement

#1984 Boruvkas Algorithm
  greedy_algorithms/boruvkas_minimum_spanning_tree.cpp
Labels: enhancement, approved

#2020 Create subset_sum.cpp
  dynamic_programming/subset_sum.cpp
Labels: enhancement

#2413 Strassen's Matrix Multiplication
  DIRECTORY.md
  bit_manipulation/travelling_salesman_using_bit_manipulation.cpp
  divide_and_conquer/strassen_matrix_multiplication.cpp
  dynamic_programming/subset_sum.cpp
  greedy_algorithms/boruvkas_minimum_spanning_tree.cpp
  range_queries/sparse_table.cpp
Labels: enhancement

#2417 fix: remove memory leak in queue
  DIRECTORY.md
  data_structures/node.hpp
  data_structures/queue.h
  data_structures/queue.hpp
  data_structures/stack.hpp
  data_structures/test_queue.cpp
  data_structures/test_stack.cpp
Labels: bugfix

#2432 chore: update FreeGLUT to v3.2.2
  graphics/CMakeLists.txt
Labels: enhancement, approved

#2416 feat: add k-nearest neighbors algorithm
  DIRECTORY.md
  machine_learning/k_nearest_neighbors.cpp
Labels: enhancement
