Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2023-06, with the labels that each got.

#2475 feat: add Kelvin to Celsius conversion algorithm
  DIRECTORY.md
  others/kelvin_to_celsius.cpp
Labels: enhancement, approved

#2477 chore: add `cpu_scheduling_algorithms` to CMake
  CMakeLists.txt
  cpu_scheduling_algorithms/CMakeLists.txt
Labels: enhancement, approved

#2471 feat: add memory game and a games folder
  CMakeLists.txt
  DIRECTORY.md
  games/CMakeLists.txt
  games/memory_game.cpp
Labels: enhancement

#2485 feat: use directory workflow from the `scripts` repository
  .github/workflows/awesome_workflow.yml
  .github/workflows/directory_writer.yml
Labels: enhancement, approved

#2481 feat: add `physics` to CMake lists
  CMakeLists.txt
  physics/CMakeLists.txt
Labels: enhancement

#2483 docs: update workflow versions in `README.md`
  README.md
Labels: enhancement, approved

#2470 feat: Add SHA-256 hashing algorithm
  DIRECTORY.md
  hashing/sha256.cpp
Labels: enhancement

#2466 fix:fit `check_factorial.cpp` to guidelines
  math/check_factorial.cpp
Labels: enhancement, approved

#2460 fix:fit check_prime.cpp to guidelines
  math/check_prime.cpp
Labels: Improvement, approved

#2441 feat: add boyer moore algorithm implementation
  .vscode/settings.json
  strings/boyer_moore.cpp
Labels: enhancement, requested changes

#2486 feat : update cmake version
  CMakeLists.txt
  math/check_factorial.cpp
  math/check_prime.cpp
  strings/boyer_moore.cpp
Labels: enhancement

#2489 Revert "feat: update CMake version"
  CMakeLists.txt
Labels: bugfix

#2457 fix: fit `armstrong_number.cpp` to guidelines
  math/aliquot_sum.cpp
  math/armstrong_number.cpp
Labels: enhancement

#2484 Next higher number with same set bits implemented
  DIRECTORY.md
  bit_manipulation/next_higher_number_with_same_number_of_set_bits.cpp
Labels: enhancement

#2465 [fix/docs]: fit `check_amicable_pair.cpp` to guidelines
  bit_manipulation/next_higher_number_with_same_number_of_set_bits.cpp
  math/armstrong_number.cpp
  math/check_amicable_pair.cpp
Labels: enhancement
