Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2023-05, with the labels that each got.

#2445 feat: add well-formed parentheses generator
  DIRECTORY.md
  backtracking/generate_parentheses.cpp
Labels: enhancement

#2461 fix: segv in `longest_palindromic_subsequence.cpp`
  dynamic_programming/longest_palindromic_subsequence.cpp
Labels: bugfix

#2467 docs: improve `longest_palindromic_subsequence.cpp`
  dynamic_programming/longest_palindromic_subsequence.cpp
Labels: enhancement, approved

#2455 feat: label PR on CI fail
  .github/workflows/awesome_workflow.yml
Labels: enhancement

#2468 fix: cover the cases `n == 0` and `m < n` in `N_bonacci`
  math/n_bonacci.cpp
Labels: Improvement

#2474 chore: add codeowners
  .github/CODEOWNERS
Labels: enhancement, approved
