Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2024-08, with the labels that each got.

#2535 fix: remove memory leak `iterative_factorial.cpp`
  math/iterative_factorial.cpp
Labels: dont-close

#2534 fix: remove memory leak `get_size_of_linked_list.cpp`
  operations_on_datastructures/get_size_of_linked_list.cpp
Labels: dont-close

#2714 chore: Make CI builds parallel
  .github/workflows/awesome_workflow.yml
Labels: enhancement

#2532 fix: remove memory leak in `library_sort.cpp`
  sorting/library_sort.cpp
Labels: dont-close

#2533 fix: memory issues in `counting_sort.cpp`
  sorting/counting_sort.cpp
Labels: dont-close

#2673 fix: use `GITHUB_ACTOR` in `git config`
  .github/workflows/gh-pages.yml
Labels: approved, dont-close

#2541 fix: remove memory leak in `sublist_search.cpp`
  search/sublist_search.cpp
Labels: Improvement, bugfix, dont-close

#2469 fix: make interface of `NCRModuloP` fail-safe
  math/ncr_modulo_p.cpp
Labels: Improvement, bugfix, dont-close

#2702 fix: compilation failure with gcc >= 13
  math/extended_euclid_algorithm.cpp
Labels: bugfix, 1st Review: Passed, dont-close

#2711 fix: fix deprecation warning for macOS
  sorting/bogo_sort.cpp
Labels: 1st Review: Passed

#2514 [fix/docs]: improve the Jump Game algorithm
  greedy_algorithms/jump_game.cpp
  greedy_algorithms/jumpgame.cpp
Labels: enhancement, approved

#2689 fix: typo in neural_network.cpp
  machine_learning/neural_network.cpp
Labels: 1st Review: Passed

#2716 Implement Trapped RainWater
  dynamic_programming/trapped_rainwater.cpp
Labels: enhancement, awaiting modification
