Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2024-09, with the labels that each got.

#2713 feat: let KMP algorithm return index
  strings/knuth_morris_pratt.cpp
Labels: Improvement, 1st Review: Passed

#2683 Rework on Stack Array Data Structure
  data_structures/stack_using_array.cpp
Labels: Improvement, 1st Review: Passed

#2692 fix: fix bug in timSort
  sorting/tim_sort.cpp
Labels: bugfix, 1st Review: Passed

#2684 Added Iterative Quick Sort
  sorting/quick_sort_iterative.cpp
Labels: automated tests are failing, requested changes
