Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2024-10, with the labels that each got.

#2743 feat: Added gale_shapley.cpp in greedy_algorithms
  greedy_algorithms/gale_shapley.cpp
Labels: approved

#2747 chore: use M_PI instead of PI parameter
  physics/ground_to_ground_projectile_motion.cpp
Labels: awaiting modification

#2752 docs: reword binary search
  search/binary_search.cpp
Labels: approved

#2725 feat: add duval's algorithm
  strings/duval.cpp
Labels: approved

#2767 feat: Add hemi-sphere area algorithm
  math/area.cpp
Labels: enhancement, hacktoberfest, approved, hacktoberfest-accepted

#2766 fix: Adding documentations, tests, and amending algorithm for gcd_of_n_numbers.cpp
  math/gcd_of_n_numbers.cpp
Labels: hacktoberfest, Improvement, approved, hacktoberfest-accepted

#2757 feat: LFU (Least frequently used) cache
  others/lfu_cache.cpp
Labels: hacktoberfest, approved, hacktoberfest-accepted

#2759 feat: Digit Separation Algorithm added
  greedy_algorithms/digit_separation.cpp
Labels: hacktoberfest, approved, hacktoberfest-accepted

#2764 feat: add recursive inserstion sort
  sorting/insertion_sort_recursive.cpp
Labels: hacktoberfest, approved, hacktoberfest-accepted

#2793 fix: Update documentations and tests for fibonacci.cpp
  math/fibonacci.cpp
Labels: approved

#2761 Create Longest_Substring_Without_Repeating_Characters.cpp
  others/longest_substring_without_repeating_characters.cpp
Labels: hacktoberfest, approved, hacktoberfest-accepted

#2800 docs, test: Fit bubble_sort into guidelines and enhance bubble sort algorithm
  sorting/bubble_sort.cpp
Labels: hacktoberfest, approved, hacktoberfest-accepted

#2780 feat: Added Exponential Probability Distribution
  probability/exponential_dist.cpp
Labels: hacktoberfest, approved, hacktoberfest-accepted

#2776 Longest Increasing subsequence using binary search most optimal approach (Modified)
  search/Longest_Increasing_Subsequence_using_binary_search.cpp
Labels: hacktoberfest, approved, hacktoberfest-accepted

#2779 docs, test: fit modular inverse fermat little theorem to contributing guidelines
  math/modular_inverse_fermat_little_theorem.cpp
Labels: hacktoberfest, approved, hacktoberfest-accepted

#2783 feat: LRU (Least recently used) cache - different implementation
  others/lru_cache2.cpp
Labels: approved, hacktoberfest-accepted

#2802 feat: Added Binary Addition Algorithm
  greedy_algorithms/binary_addition.cpp
  search/longest_increasing_subsequence_using_binary_search.cpp
Labels: approved, hacktoberfest-accepted

#2786 Create Unbounded_knapsack.cpp
  dynamic_programming/Unbounded_0_1_Knapsack.cpp
Labels: approved, hacktoberfest-accepted

#2803 docs, test: Fit Sieve of Eratosthenes to contributing guidelines
  math/sieve_of_eratosthenes.cpp
Labels: approved, hacktoberfest-accepted
