Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2024-11, with the labels that each got.

#2835 docs, test: Fit Topological Sort algorithm to contributing guidelines
  graph/topological_sort.cpp
Labels: approved, hacktoberfest-accepted

#2746 feat: update to CXX standard 17 and add CMakeLists file to directories without them
  .gitignore
  CMakeLists.txt
  README.md
  dynamic_programming/CMakeLists.txt
  dynamic_programming/abbreviation.cpp
  dynamic_programming/armstrong_number_templated.cpp
  dynamic_programming/bellman_ford.cpp
  dynamic_programming/catalan_numbers.cpp
  dynamic_programming/coin_change.cpp
  dynamic_programming/cut_rod.cpp
  dynamic_programming/edit_distance.cpp
  dynamic_programming/egg_dropping_puzzle.cpp
  dynamic_programming/floyd_warshall.cpp
  dynamic_programming/house_robber.cpp
  dynamic_programming/kadane.cpp
  dynamic_programming/kadane2.cpp
  dynamic_programming/longest_common_subsequence.cpp
  dynamic_programming/longest_increasing_subsequence.cpp
  dynamic_programming/longest_increasing_subsequence_nlogn.cpp
  dynamic_programming/minimum_edit_distance.cpp
  dynamic_programming/partition_problem.cpp
  dynamic_programming/subset_sum_dynamic.cpp
  dynamic_programming/unbounded_0_1_knapsack.cpp
  dynamic_programming/word_break.cpp
  greedy_algorithms/CMakeLists.txt
  greedy_algorithms/dijkstra_greedy.cpp
  greedy_algorithms/knapsack.cpp
  operations_on_datastructures/CMakeLists.txt
  operations_on_datastructures/circular_queue_using_array.cpp
  operations_on_datastructures/trie_multiple_search.cpp
  others/fast_integer_input.cpp
  range_queries/CMakeLists.txt
  range_queries/mo.cpp
  range_queries/segtree.cpp
  range_queries/sparse_table_range_queries.cpp
Labels: awaiting review, dont-close

#2801 feat: add non-preemptive SJF scheduling
  cpu_scheduling_algorithms/non_preemptive_sjf_scheduling.cpp
Labels: hacktoberfest, approved, hacktoberfest-accepted

#2863 test: Added to z_function test corner cases for empty text and pattern
  strings/z_function.cpp
Labels: hacktoberfest, approved, hacktoberfest-accepted

#2868 fix: incorrect exception handling in factorial function
  math/factorial.cpp
Labels: approved, hacktoberfest-accepted

#2905 chore: use annotations instead of in house linter
  .github/workflows/approved-label.yml
  .github/workflows/awesome_workflow.yml
Labels: testing

#2893 docs, tests, fix: fit fibonacci_fast to contributing guidelines
  math/fibonacci_fast.cpp
Labels: approved
