Repository TheAlgorithms/C-Plus-Plus, pull requests merged in 2025-08, with the labels that each got.

#2966 chore: remove using namespace std from queue_using_array2
  data_structures/queue_using_array2.cpp
Labels: stale

#2815 feat: add algorithm to find the number of paths in a graph using DFS
  graph/number_of_paths.cpp
Labels: approved, hacktoberfest-accepted

#2982 Added constexpr GRAVITY constant (9.80665) as per guidelines
  physics/ground_to_ground_projectile_motion.cpp
Labels: approved
